//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StampRegister.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f@sekiei.jp")]
        public string MailAddress {
            get {
                return ((string)(this["MailAddress"]));
            }
            set {
                this["MailAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copyright © 2018 Hammer. All Rights Reserved.")]
        public string Copyright {
            get {
                return ((string)(this["Copyright"]));
            }
            set {
                this["Copyright"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.1]")]
        public string BoyTitle1_en {
            get {
                return ((string)(this["BoyTitle1_en"]));
            }
            set {
                this["BoyTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.1]")]
        public string BoyTitle1_jp {
            get {
                return ((string)(this["BoyTitle1_jp"]));
            }
            set {
                this["BoyTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute & cool stickers for *** only. Enjoy LINE more by using the stickers." +
            "")]
        public string BoyDescription1_en {
            get {
                return ((string)(this["BoyDescription1_en"]));
            }
            set {
                this["BoyDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」くんのために贈るキュートでクールなお名前スタンプ「Mr.パンダ」です。ほかのバージョンとセットで長～～く愛用してくださいネ～★")]
        public string BoyDescription1_jp {
            get {
                return ((string)(this["BoyDescription1_jp"]));
            }
            set {
                this["BoyDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BoyTaste1 {
            get {
                return ((int)(this["BoyTaste1"]));
            }
            set {
                this["BoyTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int BoyChara1 {
            get {
                return ((int)(this["BoyChara1"]));
            }
            set {
                this["BoyChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.2]")]
        public string BoyTitle2_en {
            get {
                return ((string)(this["BoyTitle2_en"]));
            }
            set {
                this["BoyTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.2]")]
        public string BoyTitle2_jp {
            get {
                return ((string)(this["BoyTitle2_jp"]));
            }
            set {
                this["BoyTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.1]")]
        public string GirlTitle1_en {
            get {
                return ((string)(this["GirlTitle1_en"]));
            }
            set {
                this["GirlTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.1]")]
        public string GirlTitle1_jp {
            get {
                return ((string)(this["GirlTitle1_jp"]));
            }
            set {
                this["GirlTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute stickers for *** only. Enjoy LINE more by using the stickers.")]
        public string GirlDescription1_en {
            get {
                return ((string)(this["GirlDescription1_en"]));
            }
            set {
                this["GirlDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」ちゃんのために贈るキュートなお名前スタンプ「Missパンダ」です。ほかのバージョンとセットで長～～く可愛がってあげてくださいネ～★")]
        public string GirlDescription1_jp {
            get {
                return ((string)(this["GirlDescription1_jp"]));
            }
            set {
                this["GirlDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GirlTaste1 {
            get {
                return ((int)(this["GirlTaste1"]));
            }
            set {
                this["GirlTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int GirlChara1 {
            get {
                return ((int)(this["GirlChara1"]));
            }
            set {
                this["GirlChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.2]")]
        public string GirlTitle2_en {
            get {
                return ((string)(this["GirlTitle2_en"]));
            }
            set {
                this["GirlTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.2]")]
        public string GirlTitle2_jp {
            get {
                return ((string)(this["GirlTitle2_jp"]));
            }
            set {
                this["GirlTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameListFile {
            get {
                return ((string)(this["NameListFile"]));
            }
            set {
                this["NameListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState WindowState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["WindowState"]));
            }
            set {
                this["WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 1000, 600")]
        public global::System.Drawing.Rectangle Rectangle {
            get {
                return ((global::System.Drawing.Rectangle)(this["Rectangle"]));
            }
            set {
                this["Rectangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TagFilePath {
            get {
                return ((string)(this["TagFilePath"]));
            }
            set {
                this["TagFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.1]")]
        public string SanBoyTitle1_en {
            get {
                return ((string)(this["SanBoyTitle1_en"]));
            }
            set {
                this["SanBoyTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.1]")]
        public string SanBoyTitle1_jp {
            get {
                return ((string)(this["SanBoyTitle1_jp"]));
            }
            set {
                this["SanBoyTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.2]")]
        public string SanBoyTitle2_en {
            get {
                return ((string)(this["SanBoyTitle2_en"]));
            }
            set {
                this["SanBoyTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.2]")]
        public string SanBoyTitle2_jp {
            get {
                return ((string)(this["SanBoyTitle2_jp"]));
            }
            set {
                this["SanBoyTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute & cool stickers for *** only. Enjoy LINE more by using the stickers." +
            "")]
        public string SanBoyDescription1_en {
            get {
                return ((string)(this["SanBoyDescription1_en"]));
            }
            set {
                this["SanBoyDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」さんのために贈るキュートでクールなお名前スタンプ「Mr.パンダ」です。ほかのバージョンとセットで長～～く愛用してくださいネ～★")]
        public string SanBoyDescription1_jp {
            get {
                return ((string)(this["SanBoyDescription1_jp"]));
            }
            set {
                this["SanBoyDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SanBoyTaste1 {
            get {
                return ((int)(this["SanBoyTaste1"]));
            }
            set {
                this["SanBoyTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SanBoyChara1 {
            get {
                return ((int)(this["SanBoyChara1"]));
            }
            set {
                this["SanBoyChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.1]")]
        public string SanGirlTitle1_en {
            get {
                return ((string)(this["SanGirlTitle1_en"]));
            }
            set {
                this["SanGirlTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.1]")]
        public string SanGirlTitle1_jp {
            get {
                return ((string)(this["SanGirlTitle1_jp"]));
            }
            set {
                this["SanGirlTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.2]")]
        public string SanGirlTitle2_en {
            get {
                return ((string)(this["SanGirlTitle2_en"]));
            }
            set {
                this["SanGirlTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.2]")]
        public string SanGirlTitle2_jp {
            get {
                return ((string)(this["SanGirlTitle2_jp"]));
            }
            set {
                this["SanGirlTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute stickers for *** only. Enjoy LINE more by using the stickers.")]
        public string SanGirlDescription1_en {
            get {
                return ((string)(this["SanGirlDescription1_en"]));
            }
            set {
                this["SanGirlDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」さんのために贈るキュートなお名前スタンプ「Missパンダ」です。ほかのバージョンとセットで長～～く可愛がってあげてくださいネ～★")]
        public string SanGirlDescription1_jp {
            get {
                return ((string)(this["SanGirlDescription1_jp"]));
            }
            set {
                this["SanGirlDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SanGirlTaste1 {
            get {
                return ((int)(this["SanGirlTaste1"]));
            }
            set {
                this["SanGirlTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int SanGirlChara1 {
            get {
                return ((int)(this["SanGirlChara1"]));
            }
            set {
                this["SanGirlChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.1]")]
        public string AllBoyTitle1_en {
            get {
                return ((string)(this["AllBoyTitle1_en"]));
            }
            set {
                this["AllBoyTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.1]")]
        public string AllBoyTitle1_jp {
            get {
                return ((string)(this["AllBoyTitle1_jp"]));
            }
            set {
                this["AllBoyTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr. Panda for *** only [ver.2]")]
        public string AllBoyTitle2_en {
            get {
                return ((string)(this["AllBoyTitle2_en"]));
            }
            set {
                this["AllBoyTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Mr.パンダ [ver.2]")]
        public string AllBoyTitle2_jp {
            get {
                return ((string)(this["AllBoyTitle2_jp"]));
            }
            set {
                this["AllBoyTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute & cool stickers for *** only. Enjoy LINE more by using the stickers." +
            "")]
        public string AllBoyDescription1_en {
            get {
                return ((string)(this["AllBoyDescription1_en"]));
            }
            set {
                this["AllBoyDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」@@@のために贈るキュートでクールなお名前スタンプ「Mr.パンダ」です。ほかのバージョンとセットで長～～く愛用してくださいネ～★")]
        public string AllBoyDescription1_jp {
            get {
                return ((string)(this["AllBoyDescription1_jp"]));
            }
            set {
                this["AllBoyDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AllBoyTaste1 {
            get {
                return ((int)(this["AllBoyTaste1"]));
            }
            set {
                this["AllBoyTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int AllBoyChara1 {
            get {
                return ((int)(this["AllBoyChara1"]));
            }
            set {
                this["AllBoyChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.1]")]
        public string AllGirlTitle1_en {
            get {
                return ((string)(this["AllGirlTitle1_en"]));
            }
            set {
                this["AllGirlTitle1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.1]")]
        public string AllGirlTitle1_jp {
            get {
                return ((string)(this["AllGirlTitle1_jp"]));
            }
            set {
                this["AllGirlTitle1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miss Panda for *** only [ver.2]")]
        public string AllGirlTitle2_en {
            get {
                return ((string)(this["AllGirlTitle2_en"]));
            }
            set {
                this["AllGirlTitle2_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("***専用 Missパンダ [ver.2]")]
        public string AllGirlTitle2_jp {
            get {
                return ((string)(this["AllGirlTitle2_jp"]));
            }
            set {
                this["AllGirlTitle2_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is cute stickers for *** only. Enjoy LINE more by using the stickers.")]
        public string AllGirlDescription1_en {
            get {
                return ((string)(this["AllGirlDescription1_en"]));
            }
            set {
                this["AllGirlDescription1_en"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("世界中の「***」@@@のために贈るキュートなお名前スタンプ「Missパンダ」です。ほかのバージョンとセットで長～～く可愛がってあげてくださいネ～★")]
        public string AllGirlDescription1_jp {
            get {
                return ((string)(this["AllGirlDescription1_jp"]));
            }
            set {
                this["AllGirlDescription1_jp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AllGirlTaste1 {
            get {
                return ((int)(this["AllGirlTaste1"]));
            }
            set {
                this["AllGirlTaste1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9")]
        public int AllGirlChara1 {
            get {
                return ((int)(this["AllGirlChara1"]));
            }
            set {
                this["AllGirlChara1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100, 343, 580")]
        public global::System.Drawing.Rectangle SettingRectangle {
            get {
                return ((global::System.Drawing.Rectangle)(this["SettingRectangle"]));
            }
            set {
                this["SettingRectangle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mr.パンダ")]
        public string BoyStampName {
            get {
                return ((string)(this["BoyStampName"]));
            }
            set {
                this["BoyStampName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Missパンダ")]
        public string GirlStampName {
            get {
                return ((string)(this["GirlStampName"]));
            }
            set {
                this["GirlStampName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("JP,TW,TH,AU,US,CA,GU,BR,GB,SE,ES")]
        public string Countries {
            get {
                return ((string)(this["Countries"]));
            }
            set {
                this["Countries"] = value;
            }
        }
    }
}
